# Copyright (c) 2026 Process Mission
#
# SPDX-License-Identifier: GPL-2.0-or-later

TARGET_ARCH=mcs251
TARGET_BASE_ARCH=mcs51
TARGET_XML_FILES= mcs251-core.xml
TARGET_BIG_ENDIAN=y
TARGET_LONG_BITS=32
TARGET_NOT_USING_LEGACY_LDST_PHYS_API=y
TARGET_NOT_USING_LEGACY_NATIVE_ENDIAN_API=y
