/*
 * STC8G1K08A PCA/CCP/PWM controller
 *
 * Copyright (c) 2026 Process Mission
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 */

#ifndef HW_TIMER_STC8G_PCA_H
#define HW_TIMER_STC8G_PCA_H

#include "qom/object.h"

#define TYPE_STC8G_PCA "stc8g-pca"
OBJECT_DECLARE_SIMPLE_TYPE(Stc8gPCAState, STC8G_PCA)

enum Stc8gPCAMMIO {
    STC8G_PCA_MMIO_CCON,
    STC8G_PCA_MMIO_CMOD,
    STC8G_PCA_MMIO_CCAPM0,
    STC8G_PCA_MMIO_CCAPM1,
    STC8G_PCA_MMIO_CCAPM2,
    STC8G_PCA_MMIO_CL,
    STC8G_PCA_MMIO_CCAP0L,
    STC8G_PCA_MMIO_CCAP1L,
    STC8G_PCA_MMIO_CCAP2L,
    STC8G_PCA_MMIO_PWM0,
    STC8G_PCA_MMIO_PWM1,
    STC8G_PCA_MMIO_PWM2,
    STC8G_PCA_MMIO_CH,
    STC8G_PCA_MMIO_CCAP0H,
    STC8G_PCA_MMIO_CCAP1H,
    STC8G_PCA_MMIO_CCAP2H,
    STC8G_PCA_MMIO_REGS,
};

#endif
