#
# RISC-V system tests
#

TEST_SRC = $(SRC_PATH)/tests/gevico/tcg/riscv64
VPATH += $(TEST_SRC)

LINK_SCRIPT = $(TEST_SRC)/crt/semihost.ld
CRT_SCRIPT = $(TEST_SRC)/crt/crt.S \
             $(TEST_SRC)/crt/memory.c \
             $(TEST_SRC)/crt/console.c
LDFLAGS = -T $(LINK_SCRIPT)
CFLAGS += -I$(TEST_SRC)/crt/ \
          -g -Og -static \
          -march=rv64gcv -mabi=lp64d \
          -mcmodel=medany \
          -Wa,--noexecstack \
          -fvisibility=hidden -nostdlib \
          -Wl,--build-id=none \
          -fno-builtin -mrelax

%: %.c $(CRT_SCRIPT) $(LINK_SCRIPT)
	$(CC) $(CFLAGS) $(CRT_SCRIPT) $(LDFLAGS) $< -o $@

define QEMU_OPTS
-M $(1) -m 2G \
-display none -semihosting \
-serial stdio \
-d int \
-device loader,file=$(2) \
$(3)
endef

TEST_CASES := board-g233

define case_template
EXTRA_RUNS += run-$(1)
run-$(1): test-$(1)
	$(call run-test, $$<, $(QEMU) $(call QEMU_OPTS,g233,$$<), $$<, $(TIMEOUT))
gdbstub-$(1): test-$(1)
	$(call gdbstub-test, $$<, $(QEMU) $(call QEMU_OPTS,g233,$$<, -s -S), $$<, 3600)
endef

$(foreach case,$(TEST_CASES),$(eval $(call case_template,$(case))))

# We don't currently support the multiarch system tests
undefine MULTIARCH_TESTS
