on:
  schedule:
    - cron: '0 */30 * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  push_upstream:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: git fetch -a origin --unshallow || true
      - run: git config user.name "GitHub Actions Bot"
      - run: git config user.email "<bot@github.com>"
      - run: git remote add upstream -f https://gitlab.com/qemu-project/qemu
      - run: git checkout -b master || git checkout master
      - run: git reset --hard upstream/master
      - run: git merge origin/ci --squash --ff
      - run: mv .github/workflows/build.yml build.yml && git rm -f .github/workflows/* && mkdir -p .github/workflows/ && mv build.yml .github/workflows/ && git add .github
      - run: git commit -a -m 'ci' --signoff
      - run: git push -f --set-upstream origin master
